CREATE DATABASE ACADEMIA

USE ACADEMIA

CREATE TABLE MATRICULA (
COD_MATRICULA INT PRIMARY KEY IDENTITY (1,1),
COD_ALUNO INT FOREIGN KEY REFERENCES CADASTRO_ALUNO (COD_ALUNO),
DATA_MATRICULA DATE NOT NULL,
DATA_VENC DATE NOT NULL,
COD_FREQ INT FOREIGN KEY REFERENCES FREQUENCIA (COD_FREQ),
COD_EVENTO INT FOREIGN KEY REFERENCES EVENTO (COD_EVENTO),
COD_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSOR (COD_PROF)
) 

CREATE TABLE CADASTRO_ALUNO (
COD_ALUNO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL,
RG VARCHAR NOT NULL,
CPF INT NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE INT NOT NULL,
COD_ENDEREÇO INT FOREIGN KEY REFERENCES ENDERECO (COD_ENDERECO),
COD_PERIODO INT FOREIGN KEY REFERENCES PERIODO (COD_PERIODO)
)

CREATE TABLE PROFESSOR (
COD_PROF INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL ,
RG VARCHAR NOT NULL,
CPF INT NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE CHAR NOT NULL,
COD_PERIODO INT FOREIGN KEY REFERENCES PERIODO (COD_PERIODO),
COD_EVENTO INT FOREIGN KEY REFERENCES EVENTO (COD_EVENTO),
COD_ENDERECO INT FOREIGN KEY REFERENCES ENDERECO (COD_ENDERECO)
)

CREATE TABLE USUARIO (
COD_USUARIO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50),
USUARIO VARCHAR(10),
SENHA VARCHAR(10),
CONF_SENHA VARCHAR(10)
)


CREATE TABLE ENDERECO (
COD_ENDERECO INT PRIMARY KEY IDENTITY (1,1),
ENDERECO VARCHAR(50) NOT NULL,
NUMERO INTEGER NOT NULL,
COMPLEMENTO VARCHAR(20),
CIDADE VARCHAR (50) NOT NULL,
BAIRRO VARCHAR(50),  
UF VARCHAR(2) NOT NULL,
CEP CHAR NOT NULL
)

CREATE TABLE PERIODO (
COD_PERIODO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL
)

CREATE TABLE EVENTO (
COD_EVENTO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL,
VALOR MONEY
)


CREATE TABLE FREQUENCIA (
COD_FREQ INT PRIMARY KEY IDENTITY (1,1),
DATA_FREQ DATE NOT NULL,
HORA_ENTRADA TIME NOT NULL,
HORA_SAIDA TIME NOT NULL
)
