CREATE DATABASE CONTROLEACADEMIA1;
go

USE CONTROLEACADEMIA1;

go


CREATE TABLE ENDERECO (
COD_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
ENDERECO VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR(20),
CIDADE VARCHAR (50) NOT NULL,
BAIRRO VARCHAR(50),  
UF VARCHAR(2) NOT NULL,
CEP varchar(50) NOT NULL
);
go


CREATE TABLE EVENTO (
COD_EVENTO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL,
VALOR MONEY
);
go

CREATE TABLE CADASTRO_ALUNO (
COD_ALUNO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL,
RG VARCHAR(20) NOT NULL,
CPF VARCHAR(20) NOT NULL,
DATA_NASC VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
COD_ENDERECO INT FOREIGN KEY REFERENCES ENDERECO (COD_ENDERECO),
PERIODO VARCHAR(20)
);
go

CREATE TABLE PROFESSOR (
COD_PROF INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50) NOT NULL ,
RG VARCHAR(50) NOT NULL,
CPF VARCHAR(20) NOT NULL,
DATA_NASC VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(50) NOT NULL,
PERIODO VARCHAR (20) NOT NULL,
COD_ENDERECO INT FOREIGN KEY REFERENCES ENDERECO (COD_ENDERECO)
);
go

CREATE TABLE MATRICULA (
COD_MATRICULA INT PRIMARY KEY IDENTITY (1,1),
COD_ALUNO INT FOREIGN KEY REFERENCES CADASTRO_ALUNO (COD_ALUNO),
DATA_MATRICULA VARCHAR(50) NOT NULL,
DATA_VENC VARCHAR(50) NOT NULL,
COD_EVENTO INT FOREIGN KEY REFERENCES EVENTO (COD_EVENTO),
COD_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSOR (COD_PROF)
);
go

CREATE TABLE FREQUENCIA (
COD_FREQ INT PRIMARY KEY IDENTITY (1,1),
COD_MATRICULA INT FOREIGN KEY REFERENCES MATRICULA (COD_MATRICULA),
DATA_FREQ VARCHAR(50) NULL,
HORA_ENTRADA VARCHAR(50) NULL,
HORA_SAIDA VARCHAR(50) NULL
);
go

CREATE TABLE USUARIO (
COD_USUARIO INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50),
USUARIO VARCHAR(10),
SENHA VARCHAR(10),
CONF_SENHA VARCHAR(10)
);
go
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('ADMIN', 'ADMA', 'ADMA')
INSERT INTO ENDERECO (ENDERECO, NUMERO, COMPLEMENTO, CIDADE, BAIRRO, UF ,CEP) VALUES ('GOMES MAIA', '210','CURVA', 'SAO PAULO', 'BRASILANDIA', 'SP', 'CEP')select SCOPE_IDENTITY();
INSERT INTO EVENTO (NOME) VALUES ('MUSCULAÇÃO')
INSERT INTO CADASTRO_ALUNO(NOME, RG, CPF, DATA_NASC, TELEFONE, COD_ENDERECO, PERIODO) VALUES ('AV HUMBERTO GOMES MAIA', '2103463','242365657', '536657334', '565476868', '1', '1')
INSERT INTO MATRICULA(DATA_MATRICULA, DATA_VENC) VALUES ('05/05/2018', '05/05/2018')
INSERT INTO MATRICULA(DATA_MATRICULA, DATA_VENC) VALUES ('05052018', '05052018')

SELECT *FROM FREQUENCIA
SELECT *FROM USUARIO
SELECT * FROM CADASTRO_ALUNO
SELECT *FROM MATRICULA
SELECT *FROM PROFESSOR
SELECT *FROM ENDERECO  
SELECT *FROM EVENTO
SELECT DATA_VENC, DATA_MATRICULA, COD_MATRICULA, NOME, RG FROM MATRICULA INNER JOIN CADASTRO_ALUNO ON MATRICULA.COD_MATRICULA= CADASTRO_ALUNO.COD_ALUNO INNER JOIN ENDERECO ON CADASTRO_ALUNO.COD_ENDERECO = ENDERECO.COD_ENDERECO
 
 INSERT INTO FREQUENCIA(DATA_FREQ, HORA_ENTRADA, HORA_SAIDA, COD_MATRICULA) VALUES ('05/05/2018', '05/05/2018', '05/05/2018', 3)

 DELETE FROM FREQUENCIA
DELETE FROM EVENTO
DELETE FROM ENDERECO where COD_ENDERECO = 3
DELETE FROM MATRICULA
DELETE FROM CADASTRO_ALUNO

Select FREQUENCIA.COD_MATRICULA, NOME, DATA_FREQ, HORA_ENTRADA, HORA_SAIDA, COD_FREQ FROM MATRICULA INNER JOIN FREQUENCIA ON FREQUENCIA.COD_MATRICULA = MATRICULA.COD_MATRICULA INNER JOIN CADASTRO_ALUNO ON CADASTRO_ALUNO.COD_ALUNO = MATRICULA.COD_MATRICULA WHERE MATRICULA.COD_MATRICULA = 4 AND HORA_ENTRADA = '17:03'




SELECT FREQUENCIA.COD_FREQ FROM FREQUENCIA  WHERE COD_MATRICULA = 4